### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by ferreiro** [ZooTools/email-spell-checker#12]
Right now we manually release the library by typing `npm run release` on local development, and we copy/paste the dist files to our CDN. While this works, it's not the ideal solution given we can automate it.

Goal: Figure out what could be a good release process for the library.

## What needs to happen?

1) It should publish a new version in our CDN, so users can consume and use it directly on their websites.
2) It should publish a new version on NPM.
3) It should not allow to publish if tests don't run

## Potential solutions

Setup circle CI, and write a script in Node.js (as we do internally at [ZooTools](http://zootools.co))

1. It should build the new version
2. Publish the new version to Google Storage.
3. Upload version to NPM.

## References
* Stripe-js and their release process: https://github.com/stripe/stripe-js

**Comment by robsonsobral** [comment]
Have you considered [Drone.io](https://www.drone.io/)?
