### ISSUE TITLE
EntryPointError on BundlePhobia

### ISSUE THREAD

**Issue by robsonsobral** [ZooTools/email-spell-checker#14]
[BundlePhobia](https://bundlephobia.com/package/email-spell-checker) reports an entry point error on this package:

> We could not guess a valid entry point for this package. Perhaps the author hasn't specified one in its package.json ?

**Comment by ztoolsgithub** [comment]
hey @robsonsobral I can see it working on Bundlephobia website: https://bundlephobia.com/package/@zootools/email-spell-checker@1.11.0

can you elaborate?

![Screen Shot 2022-10-25 at 10 21 10 PM](https://user-images.githubusercontent.com/116674820/197874131-feddcfca-18d8-4c36-9023-88b7029b671c.png)

**Comment by robsonsobral** [comment]
My bad! I used `email-spell-checker` instead of `@zootools/email-spell-checker`.

I'm sorry!
