### ISSUE TITLE
Add an HTML demo

### ISSUE THREAD

**Issue by robsonsobral** [ZooTools/email-spell-checker#15]
May I suggest you to add an HTML demo to the package to make the development easier?

To put it online, as a second step, would also be good.

**Comment by ferreiro** [comment]
@robsonsobral Hey totall! Super good idea. Want to create a PR for it?

**Comment by Daijobou** [comment]
Agree with this. A JS file and an HTML example would be easier for those who want to use it in the browser.

**Comment by ferreiro** [comment]
Closing since this is now done in #24. Thanks @erayalkis
