### ISSUE TITLE
Doesn't suggest misspellings for icloud domains

### ISSUE THREAD

**Issue by roguesherlock** [ZooTools/email-spell-checker#21]
## Current Behavior

doesn't suggest misspellings for icloud.com domains

## Expected Behavior

`jorge@iclid.com` should suggest `jorge@icloud.com`

## Steps to Reproduce the Problem

https://stackblitz.com/edit/stackblitz-starters-i8edhf?file=index.js

**Comment by hashimaziz1** [comment]
I can confirm it triggers on most variations of `icloud` such as `icloid.com` and `iclod.com`, just not specifically `iclid.com`. I noticed there's a `domainThreshold` setting in the config that defaults to 2, try setting that to 3 and see if it fixes the issue?

**Comment by roguesherlock** [comment]
@hashimaziz1 thanks that totally does it!
